### PR TITLE
Reorgansing data in `FluffyChatBotDictionaries.py`

### PR DESCRIPTION
**Pull request by aneroid**
Might be easier to maintain data in separate text-based files instead of large sets and dictionaries all in one big Python file.

- `FluffyChatBotDictionaries.py` is now a module with the same name, and the data is loaded/imported in `__init__.py`.
  - So the `from FluffyChatBotDictionaries import UnitNameDict, CommanderMastery, ...` line in `ReplayAnalysis.py` needs no changes. And the referenced data structures are the same as the original.
- Moved dictionaries to `.csv` files and sets to `.txt`, while maintaining order. (Shouldn't matter for sets though.)
  - csv's have headers for human readability but are ignored when loaded.
  - txt's have no headers and are just meant to be loaded into sets, lists, etc.
  - `comastery` dicts are specifically in a `key: [value1, ..., value6]` format.
- Added functions in `_data_utils.py` which are used in FCB.init to load them appropriately
  - there is an optional `factory` parameter when loading txt's which defaults to `set` as per the original data
  - the param can be set to `list`, `frozenset`, etc. as needed
  - empty lines in either format are ignored
- All the local names and imports are `_underscored` so as not to pollute the namespace with local vars or the helper functions.
- There is _some_ size reduction since the raw data doesn't require Python delimiters.
  - Example: `UnitNames` raw dict was 48k characters. The `UnitNames.csv` is 41 KB. (In-memory size remains the same of course.)

### CODE REVIEW

**Comment by aneroid** [comment]
That just leaves `UnitCompDict` in the init file since that's a more complex structure - dict values are each a list of sets. I could move that out to a csv and add a loader specifically for it but it seems like more effort than it's worth, especially when you want to edit/maintain that data in its text-based format.

I'd recommend just moving it out to its own .py file and importing it (in init). Since that change is a bit iffy, I've left it out of this pull request.

Let me know if it makes sense _to you_ to have it that way. Would take all of 5 mins to do it, and transparently so that the import in `ReplayAnalysis.py` remains unchanged.

**Comment by thendarion** [comment]
I like the idea from over here (ie. without any stakes in the matter)

though I would totally squash those commits into one

**Comment by aneroid** [comment]
Thanks!

I had originally done it as just 2 bulk changes. Decided to break them down per data item so that once merged, FluffyMaguro could easily revert an item if he/she/they decided that it was better left in `__init__.py`. But as a bulk change, it would need to be done separately and _manually_.

As a branch, if `reorg_data` is merged with `--no-ff` (no fast forward), it keeps the main branch clean. In any case, they could still choose to merge it `--squash`ed.

**Comment by FluffyMaguro** [comment]
Thank you, I'll add that.

**Pull request merged**
